apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment çš„åå­—ï¼Œ
  # kubectl rollout restart deployment $(APP) --namespace=$(NAMESPACE)
  # æ˜¯ä»€ä¹ˆ $(APP) åå­—çš„æ›¿æ¢
  name: service-pod
  namespace: sales-system

spec:
  selector:
    matchLabels:
      # è¿™ä¸ªæ˜¯ pod çš„åå­—
      # ä¾‹å¦‚ï¼Œåœ¨æŸ¥çœ‹ logs çš„æ—¶å€™ï¼Œéœ€è¦ç”¨åˆ°è¿™ä¸ªåå­—ï¼ŒæŒ‡å®šæŸä¸€ pod
      # kubectl logs --namespace=$(NAMESPACE) -l app=service --all-containers=true -f --tail=100
      app: service

  template:
    metadata:
      labels:
        app: service

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
        - name: service-api
          # è¿™ç§å†™æ­»çš„ image èƒŒåå‚æ•°ï¼Œéœ€è¦ç‰¹åˆ«æ³¨æ„âš ï¸
          # service-arm:1.0 , 1.0 æ˜¯æŒ‡åœ¨ docker è¿›è¡Œåº”ç”¨æ‰“åŒ…çš„æ—¶å€™ï¼Œåº”ç”¨çš„æ ‡ç­¾ğŸ·ï¸ï¼Œåç»­ä¼šä¸æ–­åœ°é¢‘ç¹å˜åŠ¨çš„ã€‚ä¸åº”è¯¥å†™æ­»âŒ
          #
          image: service-arm:1.0

          ports:
            - name: service-api
              containerPort: 3000
            - name: srv-api-debug
              containerPort: 4000